import Navbar from "@/components/Navbar";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amazon-tracker",
  description: "Generated by Jaswanth",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className=" bg-sky-950 h-screen" lang="en">
      <body className={inter.className}>
        <main className="bg-sky-950 h-screen">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
